---
- hosts: all
  become: no
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Set new password for inital login
      delegate_to: 127.0.0.1
      expect:
        raw: "sshpass -p {{ old_ssh_pass }} ssh -tt ubuntu@{{ inventory_hostname }}"
        timeout: 5
        responses:
          "password:":
            # we couldn't keep the same old password
            - "{{ old_ssh_pass }}"
            - "{{ ssh_pass }}"
            - "{{ ssh_pass }}"
          # if succesfully login then quit
          "\\~\\]\\$": exit
      register: status
      changed_when: "'authentication tokens updated successfully' in status.stdout"
